### ISSUE TITLE
!hangardmod load steamId shipPositionInHangar does throw exceptions

### ISSUE THREAD

**Issue by BookBurner** [BobDaRoss/QuantumHangarIssues#34]
16:48:51.9888 [INFO]   Chat: Error (to dontburnthebooks): Exception has been thrown by the target of an invocation.
16:48:51.9888 [ERROR]  Command: Command '!hangarmod load <String NameOrSteamID> <String GridNameOrNumber> ' from 'Quantum Hangar' threw an exception. Args: 76561198023918016, 4
16:48:51.9888 [ERROR]  Command: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at QuantumHangar.Utilities.HangarChecks.AdminLoadGrid(String NameOrID, String gridNameOrEntityId) in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Utilities\HangarChecks.cs:line 762
   at QuantumHangar.AdminCommands.AdminLoad(String NameOrSteamID, String GridNameOrNumber) in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\ChatCommands.cs:line 148
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Torch.Commands.Command.TryInvoke(CommandContext context) in C:\jenkins\workspace\Torch_Torch_master\Torch\Commands\Command.cs:line 145
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at QuantumHangar.Utilities.HangarChecks.AdminLoadGrid(String NameOrID, String gridNameOrEntityId) in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Utilities\HangarChecks.cs:line 762
   at QuantumHangar.AdminCommands.AdminLoad(String NameOrSteamID, String GridNameOrNumber) in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\ChatCommands.cs:line 148
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Torch.Commands.Command.TryInvoke(CommandContext context) in C:\jenkins\workspace\Torch_Torch_master\Torch\Commands\Command.cs:line 145
16:48:51.9888 [INFO]   CommandManager: Player dontburnthebooks ran command '!hangarmod load 76561198023918016 4'
16:48:53.8642 [WARN]   HangarChecks: 1

**Comment by BobDaRoss** [comment]
ahh yeah. Need to update this.... Hold on
