### ISSUE TITLE
PCU check checks total grid's PCU against all owners

### ISSUE THREAD

**Issue by BookBurner** [BobDaRoss/QuantumHangarIssues#38]
PCU check checks the total PCU size of the grid against all owners on said grid. Not only their portions, but everything.

for example, grid has 19k PCU, only one functional block there is of another player which has 4k free PCU, it says he needs 15k more PCU, even when the other blocks were built by someone else.

Not sure if it happens every time, players report they normally withdrew the ship few hours before. So we will wait after the server restart and report if anything changes.

**Comment by BookBurner** [comment]
PS: I tried to solve it with !hangarmod load, it loaded, but threw exception and the grid didn't dissapear from the list

11:13:59.7603 [INFO]   CommandManager: Player dontburnthebooks ran command '!hangarmod list 76561198081325381'
11:14:19.8028 [INFO]   Chat:  (to dontburnthebooks): Load Complete!
11:14:19.8028 [INFO]   Chat: Error (to dontburnthebooks): Exception has been thrown by the target of an invocation.
11:14:19.8028 [ERROR]  Command: Command '!hangarmod load <String NameOrSteamID> <String GridNameOrNumber> ' from 'Quantum Hangar' threw an exception. Args: 76561198081325381, 4
11:14:19.8028 [ERROR]  Command: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at QuantumHangar.Utilities.HangarChecks.LoadGridFile(String GridName, PlayerInfo Data, GridStamp Grid) in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Utilities\HangarChecks.cs:line 2445
   at QuantumHangar.Utilities.HangarChecks.AdminLoadGrid(String NameOrID, String gridNameOrEntityId) in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Utilities\HangarChecks.cs:line 813
   at QuantumHangar.AdminCommands.AdminLoad(String NameOrSteamID, String GridNameOrNumber) in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\ChatCommands.cs:line 148
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Torch.Commands.Command.TryInvoke(CommandContext context) in C:\jenkins\workspace\Torch_Torch_master\Torch\Commands\Command.cs:line 145
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at QuantumHangar.Utilities.HangarChecks.LoadGridFile(String GridName, PlayerInfo Data, GridStamp Grid) in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Utilities\HangarChecks.cs:line 2445
   at QuantumHangar.Utilities.HangarChecks.AdminLoadGrid(String NameOrID, String gridNameOrEntityId) in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Utilities\HangarChecks.cs:line 813
   at QuantumHangar.AdminCommands.AdminLoad(String NameOrSteamID, String GridNameOrNumber) in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\ChatCommands.cs:line 148
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Torch.Commands.Command.TryInvoke(CommandContext context) in C:\jenkins\workspace\Torch_Torch_master\Torch\Commands\Command.cs:line 145

**Comment by BobDaRoss** [comment]
Yeah I fixed hangarmod load... Ill fix pcu check rn

**Comment by BobDaRoss** [comment]
Fixed
