### ISSUE TITLE
Hangar thowing exception

### ISSUE THREAD

**Issue by bodyboarder2528** [BobDaRoss/QuantumHangarIssues#39]
When checking for issues in the log i stumbled across this.
15:00:05.0125 [INFO]   Chat: Error (to LT Commander Mattman): Exception has been thrown by the target of an invocation.
15:00:05.0125 [ERROR]  Torch.Commands.Command: Command '!hangar save ' from 'Quantum Hangar' threw an exception. Args: 
15:00:05.0125 [ERROR]  Torch.Commands.Command: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidCastException: Unable to cast object of type 'Sandbox.Game.Entities.MyVoxelPhysics' to type 'Sandbox.Game.Entities.MyCubeGrid'.
   at QuantumHangar.GridMethods.FindGridList(String gridNameOrEntityId, MyCharacter character, Settings Config) in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Utilities\Utils.cs:line 401
   at QuantumHangar.Utilities.HangarChecks.GetGrids(MyCharacter character, String GridName) in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Utilities\HangarChecks.cs:line 1431
   at QuantumHangar.Utilities.HangarChecks.SaveGrid() in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Utilities\HangarChecks.cs:line 157
   at QuantumHangar.ChatCommands.Save() in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\ChatCommands.cs:line 43
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Torch.Commands.Command.TryInvoke(CommandContext context) in C:\jenkins\workspace\Torch_Torch_master\Torch\Commands\Command.cs:line 145
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidCastException: Unable to cast object of type 'Sandbox.Game.Entities.MyVoxelPhysics' to type 'Sandbox.Game.Entities.MyCubeGrid'.
   at QuantumHangar.GridMethods.FindGridList(String gridNameOrEntityId, MyCharacter character, Settings Config) in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Utilities\Utils.cs:line 401
   at QuantumHangar.Utilities.HangarChecks.GetGrids(MyCharacter character, String GridName) in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Utilities\HangarChecks.cs:line 1431
   at QuantumHangar.Utilities.HangarChecks.SaveGrid() in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Utilities\HangarChecks.cs:line 157
   at QuantumHangar.ChatCommands.Save() in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\ChatCommands.cs:line 43
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Torch.Commands.Command.TryInvoke(CommandContext context) in C:\jenkins\workspace\Torch_Torch_master\Torch\Commands\Command.cs:line 145
15:00:05.0125 [INFO]   Torch.Commands.CommandManager: Player LT Commander Mattman ran command '!hangar save'
15:00:14.5232 [INFO]   Chat: Error (to LT Commander Mattman): Exception has been thrown by the target of an invocation.
15:00:14.5232 [ERROR]  Torch.Commands.Command: Command '!hangar save ' from 'Quantum Hangar' threw an exception. Args: 
15:00:14.5232 [ERROR]  Torch.Commands.Command: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidCastException: Unable to cast object of type 'Sandbox.Game.Entities.MyVoxelPhysics' to type 'Sandbox.Game.Entities.MyCubeGrid'.
   at QuantumHangar.GridMethods.FindGridList(String gridNameOrEntityId, MyCharacter character, Settings Config) in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Utilities\Utils.cs:line 401
   at QuantumHangar.Utilities.HangarChecks.GetGrids(MyCharacter character, String GridName) in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Utilities\HangarChecks.cs:line 1431
   at QuantumHangar.Utilities.HangarChecks.SaveGrid() in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Utilities\HangarChecks.cs:line 157
   at QuantumHangar.ChatCommands.Save() in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\ChatCommands.cs:line 43
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Torch.Commands.Command.TryInvoke(CommandContext context) in C:\jenkins\workspace\Torch_Torch_master\Torch\Commands\Command.cs:line 145
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidCastException: Unable to cast object of type 'Sandbox.Game.Entities.MyVoxelPhysics' to type 'Sandbox.Game.Entities.MyCubeGrid'.
   at QuantumHangar.GridMethods.FindGridList(String gridNameOrEntityId, MyCharacter character, Settings Config) in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Utilities\Utils.cs:line 401
   at QuantumHangar.Utilities.HangarChecks.GetGrids(MyCharacter character, String GridName) in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Utilities\HangarChecks.cs:line 1431
   at QuantumHangar.Utilities.HangarChecks.SaveGrid() in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Utilities\HangarChecks.cs:line 157
   at QuantumHangar.ChatCommands.Save() in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\ChatCommands.cs:line 43
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Torch.Commands.Command.TryInvoke(CommandContext context) in C:\jenkins\workspace\Torch_Torch_master\Torch\Commands\Command.cs:line 145
15:00:14.5232 [INFO]   Torch.Commands.CommandManager: Player LT Commander Mattman ran command '!hangar save'
15:00:16.2097 [INFO]   Chat: Error (to LT Commander Mattman): Exception has been thrown by the target of an invocation.
15:00:16.2097 [ERROR]  Torch.Commands.Command: Command '!hangar save ' from 'Quantum Hangar' threw an exception. Args: 
15:00:16.2097 [ERROR]  Torch.Commands.Command: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidCastException: Unable to cast object of type 'Sandbox.Game.Entities.MyVoxelPhysics' to type 'Sandbox.Game.Entities.MyCubeGrid'.
   at QuantumHangar.GridMethods.FindGridList(String gridNameOrEntityId, MyCharacter character, Settings Config) in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Utilities\Utils.cs:line 401
   at QuantumHangar.Utilities.HangarChecks.GetGrids(MyCharacter character, String GridName) in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Utilities\HangarChecks.cs:line 1431
   at QuantumHangar.Utilities.HangarChecks.SaveGrid() in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Utilities\HangarChecks.cs:line 157
   at QuantumHangar.ChatCommands.Save() in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\ChatCommands.cs:line 43
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Torch.Commands.Command.TryInvoke(CommandContext context) in C:\jenkins\workspace\Torch_Torch_master\Torch\Commands\Command.cs:line 145
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidCastException: Unable to cast object of type 'Sandbox.Game.Entities.MyVoxelPhysics' to type 'Sandbox.Game.Entities.MyCubeGrid'.
   at QuantumHangar.GridMethods.FindGridList(String gridNameOrEntityId, MyCharacter character, Settings Config) in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Utilities\Utils.cs:line 401
   at QuantumHangar.Utilities.HangarChecks.GetGrids(MyCharacter character, String GridName) in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Utilities\HangarChecks.cs:line 1431
   at QuantumHangar.Utilities.HangarChecks.SaveGrid() in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Utilities\HangarChecks.cs:line 157
   at QuantumHangar.ChatCommands.Save() in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\ChatCommands.cs:line 43
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Torch.Commands.Command.TryInvoke(CommandContext context) in C:\jenkins\workspace\Torch_Torch_master\Torch\Commands\Command.cs:line 145
15:00:16.2097 [INFO]   Torch.Commands.CommandManager: Player LT Commander Mattman ran command '!hangar save'
15:00:17.4754 [INFO]   Chat: Error (to LT Commander Mattman): Exception has been thrown by the target of an invocation.
15:00:17.4754 [ERROR]  Torch.Commands.Command: Command '!hangar save ' from 'Quantum Hangar' threw an exception. Args: 
15:00:17.4754 [ERROR]  Torch.Commands.Command: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidCastException: Unable to cast object of type 'Sandbox.Game.Entities.MyVoxelPhysics' to type 'Sandbox.Game.Entities.MyCubeGrid'.
   at QuantumHangar.GridMethods.FindGridList(String gridNameOrEntityId, MyCharacter character, Settings Config) in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Utilities\Utils.cs:line 401
   at QuantumHangar.Utilities.HangarChecks.GetGrids(MyCharacter character, String GridName) in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Utilities\HangarChecks.cs:line 1431
   at QuantumHangar.Utilities.HangarChecks.SaveGrid() in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Utilities\HangarChecks.cs:line 157
   at QuantumHangar.ChatCommands.Save() in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\ChatCommands.cs:line 43
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Torch.Commands.Command.TryInvoke(CommandContext context) in C:\jenkins\workspace\Torch_Torch_master\Torch\Commands\Command.cs:line 145
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidCastException: Unable to cast object of type 'Sandbox.Game.Entities.MyVoxelPhysics' to type 'Sandbox.Game.Entities.MyCubeGrid'.
   at QuantumHangar.GridMethods.FindGridList(String gridNameOrEntityId, MyCharacter character, Settings Config) in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Utilities\Utils.cs:line 401
   at QuantumHangar.Utilities.HangarChecks.GetGrids(MyCharacter character, String GridName) in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Utilities\HangarChecks.cs:line 1431
   at QuantumHangar.Utilities.HangarChecks.SaveGrid() in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Utilities\HangarChecks.cs:line 157
   at QuantumHangar.ChatCommands.Save() in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\ChatCommands.cs:line 43
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Torch.Commands.Command.TryInvoke(CommandContext context) in C:\jenkins\workspace\Torch_Torch_master\Torch\Commands\Command.cs:line 145
15:00:17.4754 [INFO]   Torch.Commands.CommandManager: Player LT Commander Mattman ran command '!hangar save'
15:00:18.6393 [INFO]   Chat: Error (to LT Commander Mattman): Exception has been thrown by the target of an invocation.
15:00:18.6393 [ERROR]  Torch.Commands.Command: Command '!hangar save ' from 'Quantum Hangar' threw an exception. Args: 
15:00:18.6393 [ERROR]  Torch.Commands.Command: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidCastException: Unable to cast object of type 'Sandbox.Game.Entities.MyVoxelPhysics' to type 'Sandbox.Game.Entities.MyCubeGrid'.
   at QuantumHangar.GridMethods.FindGridList(String gridNameOrEntityId, MyCharacter character, Settings Config) in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Utilities\Utils.cs:line 401
   at QuantumHangar.Utilities.HangarChecks.GetGrids(MyCharacter character, String GridName) in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Utilities\HangarChecks.cs:line 1431
   at QuantumHangar.Utilities.HangarChecks.SaveGrid() in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Utilities\HangarChecks.cs:line 157
   at QuantumHangar.ChatCommands.Save() in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\ChatCommands.cs:line 43
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Torch.Commands.Command.TryInvoke(CommandContext context) in C:\jenkins\workspace\Torch_Torch_master\Torch\Commands\Command.cs:line 145
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidCastException: Unable to cast object of type 'Sandbox.Game.Entities.MyVoxelPhysics' to type 'Sandbox.Game.Entities.MyCubeGrid'.
   at QuantumHangar.GridMethods.FindGridList(String gridNameOrEntityId, MyCharacter character, Settings Config) in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Utilities\Utils.cs:line 401
   at QuantumHangar.Utilities.HangarChecks.GetGrids(MyCharacter character, String GridName) in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Utilities\HangarChecks.cs:line 1431
   at QuantumHangar.Utilities.HangarChecks.SaveGrid() in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Utilities\HangarChecks.cs:line 157
   at QuantumHangar.ChatCommands.Save() in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\ChatCommands.cs:line 43
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Torch.Commands.Command.TryInvoke(CommandContext context) in C:\jenkins\workspace\Torch_Torch_master\Torch\Commands\Command.cs:line 145
15:00:18.6393 [INFO]   Torch.Commands.CommandManager: Player LT Commander Mattman ran command '!hangar save'
15:00:19.7224 [INFO]   Chat: Error (to LT Commander Mattman): Exception has been thrown by the target of an invocation.
15:00:19.7224 [ERROR]  Torch.Commands.Command: Command '!hangar save ' from 'Quantum Hangar' threw an exception. Args: 
15:00:19.7224 [ERROR]  Torch.Commands.Command: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidCastException: Unable to cast object of type 'Sandbox.Game.Entities.MyVoxelPhysics' to type 'Sandbox.Game.Entities.MyCubeGrid'.
   at QuantumHangar.GridMethods.FindGridList(String gridNameOrEntityId, MyCharacter character, Settings Config) in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Utilities\Utils.cs:line 401
   at QuantumHangar.Utilities.HangarChecks.GetGrids(MyCharacter character, String GridName) in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Utilities\HangarChecks.cs:line 1431
   at QuantumHangar.Utilities.HangarChecks.SaveGrid() in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Utilities\HangarChecks.cs:line 157
   at QuantumHangar.ChatCommands.Save() in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\ChatCommands.cs:line 43
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Torch.Commands.Command.TryInvoke(CommandContext context) in C:\jenkins\workspace\Torch_Torch_master\Torch\Commands\Command.cs:line 145
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidCastException: Unable to cast object of type 'Sandbox.Game.Entities.MyVoxelPhysics' to type 'Sandbox.Game.Entities.MyCubeGrid'.
   at QuantumHangar.GridMethods.FindGridList(String gridNameOrEntityId, MyCharacter character, Settings Config) in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Utilities\Utils.cs:line 401
   at QuantumHangar.Utilities.HangarChecks.GetGrids(MyCharacter character, String GridName) in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Utilities\HangarChecks.cs:line 1431
   at QuantumHangar.Utilities.HangarChecks.SaveGrid() in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Utilities\HangarChecks.cs:line 157
   at QuantumHangar.ChatCommands.Save() in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\ChatCommands.cs:line 43
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Torch.Commands.Command.TryInvoke(CommandContext context) in C:\jenkins\workspace\Torch_Torch_master\Torch\Commands\Command.cs:line 145
15:00:19.7224 [INFO]   Torch.Commands.CommandManager: Player LT Commander Mattman ran command '!hangar save'
15:00:20.7895 [INFO]   Chat: Error (to LT Commander Mattman): Exception has been thrown by the target of an invocation.
15:00:20.7895 [ERROR]  Torch.Commands.Command: Command '!hangar save ' from 'Quantum Hangar' threw an exception. Args: 
15:00:20.7895 [ERROR]  Torch.Commands.Command: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidCastException: Unable to cast object of type 'Sandbox.Game.Entities.MyVoxelPhysics' to type 'Sandbox.Game.Entities.MyCubeGrid'.
   at QuantumHangar.GridMethods.FindGridList(String gridNameOrEntityId, MyCharacter character, Settings Config) in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Utilities\Utils.cs:line 401
   at QuantumHangar.Utilities.HangarChecks.GetGrids(MyCharacter character, String GridName) in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Utilities\HangarChecks.cs:line 1431
   at QuantumHangar.Utilities.HangarChecks.SaveGrid() in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Utilities\HangarChecks.cs:line 157
   at QuantumHangar.ChatCommands.Save() in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\ChatCommands.cs:line 43
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Torch.Commands.Command.TryInvoke(CommandContext context) in C:\jenkins\workspace\Torch_Torch_master\Torch\Commands\Command.cs:line 145
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidCastException: Unable to cast object of type 'Sandbox.Game.Entities.MyVoxelPhysics' to type 'Sandbox.Game.Entities.MyCubeGrid'.
   at QuantumHangar.GridMethods.FindGridList(String gridNameOrEntityId, MyCharacter character, Settings Config) in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Utilities\Utils.cs:line 401
   at QuantumHangar.Utilities.HangarChecks.GetGrids(MyCharacter character, String GridName) in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Utilities\HangarChecks.cs:line 1431
   at QuantumHangar.Utilities.HangarChecks.SaveGrid() in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Utilities\HangarChecks.cs:line 157
   at QuantumHangar.ChatCommands.Save() in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\ChatCommands.cs:line 43
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Torch.Commands.Command.TryInvoke(CommandContext context) in C:\jenkins\workspace\Torch_Torch_master\Torch\Commands\Command.cs:line 145
15:00:20.7895 [INFO]   Torch.Commands.CommandManager: Player LT Commander Mattman ran command '!hangar save'
15:00:21.8397 [INFO]   Chat: Error (to LT Commander Mattman): Exception has been thrown by the target of an invocation.
15:00:21.8397 [ERROR]  Torch.Commands.Command: Command '!hangar save ' from 'Quantum Hangar' threw an exception. Args: 
15:00:21.8397 [ERROR]  Torch.Commands.Command: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidCastException: Unable to cast object of type 'Sandbox.Game.Entities.MyVoxelPhysics' to type 'Sandbox.Game.Entities.MyCubeGrid'.
   at QuantumHangar.GridMethods.FindGridList(String gridNameOrEntityId, MyCharacter character, Settings Config) in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Utilities\Utils.cs:line 401
   at QuantumHangar.Utilities.HangarChecks.GetGrids(MyCharacter character, String GridName) in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Utilities\HangarChecks.cs:line 1431
   at QuantumHangar.Utilities.HangarChecks.SaveGrid() in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Utilities\HangarChecks.cs:line 157
   at QuantumHangar.ChatCommands.Save() in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\ChatCommands.cs:line 43
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Torch.Commands.Command.TryInvoke(CommandContext context) in C:\jenkins\workspace\Torch_Torch_master\Torch\Commands\Command.cs:line 145
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidCastException: Unable to cast object of type 'Sandbox.Game.Entities.MyVoxelPhysics' to type 'Sandbox.Game.Entities.MyCubeGrid'.
   at QuantumHangar.GridMethods.FindGridList(String gridNameOrEntityId, MyCharacter character, Settings Config) in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Utilities\Utils.cs:line 401
   at QuantumHangar.Utilities.HangarChecks.GetGrids(MyCharacter character, String GridName) in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Utilities\HangarChecks.cs:line 1431
   at QuantumHangar.Utilities.HangarChecks.SaveGrid() in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Utilities\HangarChecks.cs:line 157
   at QuantumHangar.ChatCommands.Save() in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\ChatCommands.cs:line 43
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Torch.Commands.Command.TryInvoke(CommandContext context) in C:\jenkins\workspace\Torch_Torch_master\Torch\Commands\Command.cs:line 145
15:00:21.8397 [INFO]   Torch.Commands.CommandManager: Player LT Commander Mattman ran command '!hangar save'
15:00:32.9761 [INFO]   Torch.Commands.CommandManager: Player LT Commander Mattman ran command '!longhelp'

I then loaded a ship myself and go this screenshot
![unknown-58](https://user-images.githubusercontent.com/49468427/90063687-1abbbf00-dd2d-11ea-8800-1a9df2c3a25e.png)
So i checked the log and saw this.

19:28:13.3324 [INFO]   Chat:  (to bodyboarder2528): Load Complete!
19:28:13.3324 [INFO]   Chat: Error (to bodyboarder2528): Exception has been thrown by the target of an invocation.
19:28:13.3324 [ERROR]  Torch.Commands.Command: Command '!hangarmod load <String NameOrSteamID> <String GridNameOrNumber> ' from 'Quantum Hangar' threw an exception. Args: bodyboarder2528, 1
19:28:13.3324 [ERROR]  Torch.Commands.Command: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at QuantumHangar.Utilities.HangarChecks.LoadGridFile(String GridName, PlayerInfo Data, GridStamp Grid) in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Utilities\HangarChecks.cs:line 2445
   at QuantumHangar.Utilities.HangarChecks.AdminLoadGrid(String NameOrID, String gridNameOrEntityId) in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Utilities\HangarChecks.cs:line 813
   at QuantumHangar.AdminCommands.AdminLoad(String NameOrSteamID, String GridNameOrNumber) in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\ChatCommands.cs:line 148
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Torch.Commands.Command.TryInvoke(CommandContext context) in C:\jenkins\workspace\Torch_Torch_master\Torch\Commands\Command.cs:line 145
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at QuantumHangar.Utilities.HangarChecks.LoadGridFile(String GridName, PlayerInfo Data, GridStamp Grid) in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Utilities\HangarChecks.cs:line 2445
   at QuantumHangar.Utilities.HangarChecks.AdminLoadGrid(String NameOrID, String gridNameOrEntityId) in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Utilities\HangarChecks.cs:line 813
   at QuantumHangar.AdminCommands.AdminLoad(String NameOrSteamID, String GridNameOrNumber) in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\ChatCommands.cs:line 148
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Torch.Commands.Command.TryInvoke(CommandContext context) in C:\jenkins\workspace\Torch_Torch_master\Torch\Commands\Command.cs:line 145
19:28:13.3723 [INFO]   Torch.Commands.CommandManager: Player bodyboarder2528 ran command '!hangarmod load bodyboarder2528 1'

**Comment by BobDaRoss** [comment]
Hmmm. looks like you were attached to a voxel

**Comment by BobDaRoss** [comment]
Ill fix

**Comment by bodyboarder2528** [comment]
For bodyboarder2528 one or the other guy?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by BobDaRoss** [comment]
Didnt even see the other one.. hold up

**Comment by bodyboarder2528** [comment]
the bodyboarder2528 one is loading using !hangarmod load

**Comment by BobDaRoss** [comment]
I see

**Comment by BobDaRoss** [comment]
Fixed

**Comment by bodyboarder2528** [comment]
thanks
